RESEARCHERMODELS = {
	"models/bmscientistcits/p_female_01.mdl",
	"models/bmscientistcits/p_female_02.mdl",
	"models/bmscientistcits/p_female_03.mdl",
	"models/bmscientistcits/p_female_04.mdl",
	"models/bmscientistcits/p_female_06.mdl",
	"models/bmscientistcits/p_female_07.mdl",
	"models/bmscientistcits/p_male_01.mdl",
	"models/bmscientistcits/p_male_02.mdl",
	"models/bmscientistcits/p_male_03.mdl",
	"models/bmscientistcits/p_male_04.mdl",
	"models/bmscientistcits/p_male_05.mdl",
	"models/bmscientistcits/p_male_06.mdl",
	"models/bmscientistcits/p_male_07.mdl",
	"models/bmscientistcits/p_male_08.mdl",
	"models/bmscientistcits/p_male_09.mdl",
	"models/bmscientistcits/p_male_10.mdl",
	"models/scp/apsci_cohrt.mdl",
	"models/scp/apsci_male_02.mdl",
	"models/scp/apsci_male_03.mdl",
	"models/scp/apsci_male_05.mdl",
	"models/scp/apsci_male_07.mdl",
	"models/scp/apsci_male_08.mdl",
	"models/scp/apsci_male_09.mdl",
}
CHAOSMODELS = {
	/*"models/kerry/merriweather1.mdl",
	"models/kerry/merriweather2.mdl",
	"models/kerry/merriweather3.mdl",
	"models/kerry/merriweather4.mdl",
	"models/kerry/merriweather5.mdl",
	"models/kerry/merriweather6.mdl",
	"models/kerry/merriweather7.mdl",
	"models/kerry/merriweather8.mdl",*/
	"models/kerry/player/merriweather/male_01.mdl",
	"models/kerry/player/merriweather/male_02.mdl",
	"models/kerry/player/merriweather/male_03.mdl",
	"models/kerry/player/merriweather/male_04.mdl",
	"models/kerry/player/merriweather/male_05.mdl",
	"models/kerry/player/merriweather/male_06.mdl",
	"models/kerry/player/merriweather/male_07.mdl",
	"models/kerry/player/merriweather/male_08.mdl",
	"models/kerry/player/merriweather/male_09.mdl",
}
SECURITYMODELS = {
	"models/npc/portal/Male_02_Garde.mdl",
	"models/npc/portal/Male_04_Garde.mdl",
	"models/npc/portal/Male_05_Garde.mdl",
	"models/npc/portal/Male_06_Garde.mdl",
	"models/npc/portal/Male_07_Garde.mdl",
	"models/npc/portal/Male_08_Garde.mdl",
	"models/npc/portal/Male_09_Garde.mdl",
}
CLASSDMODELS = {
	"models/player/kerry/class_d_1.mdl",
	"models/player/kerry/class_d_2.mdl",
	"models/player/kerry/class_d_3.mdl",
	"models/player/kerry/class_d_4.mdl",
	"models/player/kerry/class_d_5.mdl",
	"models/player/kerry/class_d_6.mdl",
	"models/player/kerry/class_d_7.mdl",
}
VETERANMODELS = {
	"models/player/kerry/Class_Jan_2.mdl",
	"models/player/kerry/Class_Jan_3.mdl",
	"models/player/kerry/Class_Jan_4.mdl",
	"models/player/kerry/Class_Jan_5.mdl",
	"models/player/kerry/Class_Jan_6.mdl",
	"models/player/kerry/Class_Jan_7.mdl",
}
SCOUTDMODELS = {
	"models/player/cheddar/class_d/scout/scout_art.mdl",
	"models/player/cheddar/class_d/scout/scout_mike.mdl",
	"models/player/cheddar/class_d/scout/scout_vance.mdl",
}
MEDICMODELS = {
	"models/player/portal/male_01_medic.mdl",
	"models/player/portal/male_02_medic.mdl",
	"models/player/portal/male_03_medic.mdl",
	"models/player/portal/male_04_medic.mdl",
	"models/player/portal/male_05_medic.mdl",
	"models/player/portal/male_06_medic.mdl",
	"models/player/portal/male_07_medic.mdl",
}
CICMODELS = {
	"models/scp/jumpsuitm1.mdl",
	"models/scp/jumpsuitm2.mdl",
	"models/scp/jumpsuitm3.mdl",
	"models/scp/jumpsuitm4.mdl",
	"models/scp/jumpsuitm5.mdl",
	"models/scp/jumpsuitm6.mdl",
	"models/scp/jumpsuitm7.mdl",
	"models/scp/jumpsuitm8.mdl",
	"models/scp/jumpsuitm9.mdl",
}

ALLCLASSES = {
	classds = {
		name = "Class D Personell",
		color = Color(255, 130, 0),
		roles = {
			{name = ROLES.ROLE_CLASSD,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {},
			 keycard = "",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 level = 0,
			 customcheck = nil,
			 flashlight = false,
			 max = 0
			},
			{name = ROLES.ROLE_CLASSD,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {"Keycard Level 1"},
			 keycard = "safe",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 level = 0,
			 customcheck = nil,
			 flashlight = false,
			 max = 0
			},
			{name = ROLES.ROLE_VETERAN,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id", "weapon_piss"},
			 showweapons = {"Keycard Level 1", "Jarate (25%)"},
			 keycard = "safe",
			 ammo = {{"weapon_piss", 1}},
			 health = 120,
			 armor = 0,
			 walkspeed = 1.1,
			 runspeed = 1.1,
			 jumppower = 1.1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 6,
			 max = 2
			},
			{name = ROLES.ROLE_SCOUT_D,
			 team = TEAM_CLASSD,
			 		weapons = {"br_holster", "br_id", "item_radio", "weapon_pocket_knife"},
			 showweapons = {"Keycard Level 2", "Radio (50%)", "Pocket Knife (25%)"},
			 keycard = "euclid",
			 ammo = {},
			 health = 110,
			 armor = 0,
			 walkspeed = 1.2,
			 runspeed = 1.2,
			 jumppower = 1.2,
			 vest = nil,
			 models = SCOUTDMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 4,
			 max = 2
			},
					{name = ROLES.ROLE_FAT_D,
		 team = TEAM_CLASSD,
		 weapons = {"br_holster", "br_id"},
		 showweapons = {"Keycard Level 1"},
		 keycard = "safe",
		 ammo = {},
		 health = 150,
		 armor = 0,
		 walkspeed = 0.8,
		 runspeed = 0.9,
		 jumppower = 0.7,
		 vest = nil,
		 models = CLASSDMODELS,
		 showmodel = nil,
		 flashlight = true,
		 level = 2,
		 max = 2,
		 fatbelly = true
		},
		{name = ROLES.ROLE_SKINNY_D,
		 team = TEAM_CLASSD,
		 weapons = {"br_holster", "br_id"},
		 showweapons = {"Keycard Level 1"},
		 keycard = "safe",
		 ammo = {},
		 health = 80,
		 armor = 0,
		 walkspeed = 1.3,
		 runspeed = 1.4,
		 jumppower = 1.3,
		 vest = nil,
		 models = CLASSDMODELS,
		 showmodel = nil,
		 flashlight = true,
		 level = 1,
		 max = 1,
		 skinnybody = true
		},

		{name = ROLES.ROLE_SCP527,
		 team = TEAM_CLASSD,
		 weapons = {"br_holster", "br_id"},
		 showweapons = {"No Keycard"},
		 keycard = "",
		 ammo = {},
		 health = 100,
		 armor = 0,
		 walkspeed = 1.0,
		 runspeed = 1.0,
		 jumppower = 1.0,
		 vest = nil,
		 models = {"models/scp_527/scp_527.mdl"},
		 showmodel = "models/scp_527/scp_527.mdl",
		 flashlight = true,
		 level = 3,
		 max = 1
		},
			{name = ROLES.ROLE_CIC,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "weapon_zeus"},
			 showweapons = {"Keycard Level 1", "Taser"},
			 keycard = "safe",
			 ammo = {{"weapon_zeus", 1}},
			 health = 120,
			 armor = 0,
			 walkspeed = 1.1,
			 runspeed = 1.1,
			 jumppower = 1.1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 9,
			 max = 1
			},
					{name = ROLES.ROLE_DCLASS_INFECTED,
		 team = TEAM_CLASSD,
		 weapons = {"br_holster", "br_id"},
		 showweapons = {"No Keycard", "Viral Infection"},
		 keycard = "",
		 ammo = {},
		 health = 80,
		 armor = 0,
		 walkspeed = 0.9,
		 runspeed = 0.9,
		 jumppower = 1,
		 vest = nil,
		 models = {"models/snood_17/citizen_17_snood_pm.mdl"},
		 showmodel = "models/snood_17/citizen_17_snood_pm.mdl",
		 flashlight = false,
		 level = 1,
		 max = 1
		},
		{name = ROLES.ROLE_THIEF_D,
		 team = TEAM_CLASSD,
		 weapons = {"br_holster", "br_id"},
		 showweapons = {"Keycard Level 1", "Weapon Theft (Passive)"},
		 keycard = "safe",
		 ammo = {},
		 health = 90,
		 armor = 0,
		 walkspeed = 1.1,
		 runspeed = 1.1,
		 jumppower = 1.0,
		 vest = nil,
		 models = CLASSDMODELS,
		 showmodel = nil,
		 flashlight = true,
		 level = 2,
			 max = 1
			}
		}
	},
	researchers = {
		name = "Unarmed Site Staff",
		color = Color(66, 188, 244),
		roles = {
			{name = ROLES.ROLE_RES,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {"Keycard Level 1"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = RESEARCHERMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 0,
			 max = 0
			},
			{name = ROLES.ROLE_MEDIC,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "item_ultramedkit"},
			 showweapons = {"Researcher Keycard", "Med Kit"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = MEDICMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 1,
			 max = 2
			},
			{name = ROLES.ROLE_NO3,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg"},
			 showweapons = {"Radio", "NVG", "Researcher Keycard"},
			 keycard = "res",
			 ammo = {},
			 health = 150,
			 armor = 0,
			 walkspeed = 1.05,
			 runspeed = 1.05,
			 jumppower = 1.05,
			 vest = nil,
			 models = RESEARCHERMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 8,
			 max = 1
			},
			{name = ROLES.ROLE_JANITOR,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "weapon_broom"},
			 showweapons = {"Keycard Level 1", "Broom"},
			 keycard = "safe",
			 ammo = {},
			 health = 90,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = VETERANMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 1,
			 max = 1
			},
			{name = ROLES.ROLE_VIP,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_pocket_knife"},
			 showweapons = {"Checkpoint Security Keycard", "Radio", "Pocket Knife (25%)"},
			 keycard = "cps",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/male_09_vip/vip_player/male_09_vip_player.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 3,
			 max = 1,
			 bodygroups = {{0, 2}, {1, 2}, {2, 1}}
			},
			{name = ROLES.ROLE_CLEARANCE_TECH,
			 team = TEAM_SCI,
			 				 		weapons = {"br_holster", "br_id", "item_radio", "weapon_doorcontrol"},
		 showweapons = {"Researcher Keycard", "Radio", "Door Controller"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/player/cheddar/bms/bms_technician.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 2,
			 max = 1,
			 bodygroups_random = {{0, {0, 14}}, {1, {1, 1}}, {2, {0, 3}}}
			},
			{name = ROLES.ROLE_ENGINEER,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_crowbar"},
			 showweapons = {"Researcher Keycard", "Radio", "Crowbar"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/worker_04/worker_04.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 2,
			 max = 1,
			},
			{name = ROLES.ROLE_COOK,
			 team = TEAM_SCI,
			 		weapons = {"br_holster", "br_id", "weapon_doner_knife"},
			 showweapons = {"Researcher Keycard", "Doner Knife", "Kebab Stand Spawner"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/fearless/chef1.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 1,
			 max = 1
			},
			{name = ROLES.ROLE_DRHOUSE,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "weapon_breach_syringe", "weapon_house_canebar"},
			 showweapons = {"Researcher Keycard", "Medical Syringe", "House Canebar"},
			 keycard = "res",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/bunny/doctor_house/doctor_house.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 2,
			 max = 1
			},
			{name = ROLES.ROLE_PSYCHOLOGIST,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_pencil"},
			 showweapons = {"Researcher Keycard", "Radio", "Therapeutic Pencil"},
			 keycard = "res",
			 ammo = {},
			 health = 110,
			 armor = 0,
			 walkspeed = 1.0,
			 runspeed = 1.0,
			 jumppower = 1.0,
			 vest = nil,
			 models = {"models/player/dr_schwaiger.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 2,
			 max = 1
			},
		}
	},
	security = {
		name = "Armed Site Security",
		color = Color(0, 100, 255),
		roles = {
			{name = ROLES.ROLE_SECURITY, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_mp5"},
			 showweapons = {"MTF Keycard", "Radio", "Stunstick", "MP5"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_security",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_sci.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 0,
			},
			{name = ROLES.ROLE_MTFGUARD, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_mp5"},
			 showweapons = {"MTF Keycard", "Radio", "Stunstick", "MP5"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_noob.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 2,
			 max = 10,
			},
			{name = ROLES.ROLE_MTF_HEAVY_SUPPORT, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_rinic_spas12"},
			 showweapons = {"MTF Keycard", "Radio", "Stunstick", "SPAS-12"},
			 keycard = "mtf",
			 ammo = {},
			 health = 170,
			 armor = 0,
			 walkspeed = 0.75,
			 runspeed = 0.85,
			 jumppower = 0.8,
			 vest = "armor_heavysupport",
			 models = SECURITYMODELS,
			 showmodel = "models/scp_mtf_russian/mtf_rus_02.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 1,
			},
			{name = ROLES.ROLE_SECURITY_DROID, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_mp5"},
			 showweapons = {"MTF Keycard", "Radio", "Stunstick", "MP5"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = nil,
			 models = {"models/mass effect 2/player/player/loki_mech.mdl"},
			 showmodel = "models/mass effect 2/player/player/loki_mech.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 2,
			 max = 2,
			},

			{name = ROLES.ROLE_CHAOSSPY, 
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_mp5"},
			 showweapons = {"MTF Keycard", "Radio", "Stunstick", "MP5"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_noob.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 2,
			},
			{name = ROLES.ROLE_MTFL, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "item_cameraview", "weapon_stunstick", "cw_ump45"},
			 showweapons = {"MTF Keycard", "Radio", "NVG", "Camera View", "Stunstick", "UMP .45"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.87,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfl",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_left.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 2,
			},
			{name = ROLES.ROLE_CSECURITY,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_cameraview", "weapon_stunstick", "cw_g36c"},
			 showweapons = {"MTF Keycard", "Radio", "Camera View", "Stunstick", "G36C"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_csecurity",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/soldier_1.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 4,
			 max = 1,
			},
			{name = ROLES.ROLE_MTFMEDIC, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_ultramedkit", "weapon_stunstick", "cw_scarh"},
			 showweapons = {"MTF Keycard", "Radio", "Medkit", "Stunstick", "SCAR-H"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfmedic",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_med.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 1,
			},
			{name = ROLES.ROLE_MTFCOM, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "item_cameraview", "weapon_bodycam_tablet", "weapon_stunstick", "cw_ar15"},
			 showweapons = {"Commander Keycard", "Radio", "NVG", "Camera View", "Bodycam Tablet", "Stunstick", "AR-15"},
			 keycard = "com",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfcom",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/captain.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 6,
			 max = 1,
			},
			{name = ROLES.ROLE_SD, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_cameraview", "weapon_stunstick", "cw_fiveseven"},
			 showweapons = {"Keycard Level OMNI", "Radio", "Camera View", "Stunstick", "Fiveseven"},
			 keycard = "omni",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/player/breen.mdl"},
			 showmodel = "models/player/breen.mdl",
			 pmcolor = Color(0,0,0),
			 flashlight = true,
			 level = 6,
			 max = 1,
			},
			{name = ROLES.ROLE_HAZMAT, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "weapon_stunstick", "cw_m14"},
			 showweapons = {"MTF Keycard", "Radio", "NVG", "Stunstick", "M14 EBR"},
			 keycard = "mtf",
			 ammo = {},
			 health = 125,
			 armor = 50,
			 walkspeed = 0.93,
			 runspeed = 0.98,
			 jumppower = 0.92,
			 vest = "armor_hazmat",
			 models = SECURITYMODELS,
			 showmodel = "models/che_pm.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 8,
			 max = 1,
			},
			{name = ROLES.ROLE_O5, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_cameraview", "weapon_stunstick", "cw_deagle", "weapon_zeus"},
			 showweapons = {"Keycard Level OMNI", "Radio", "Camera View", "Stunstick", "Desert Eagle", "Taser"},
			 keycard = "omni",
			 ammo = {{"weapon_zeus", 3}},
			 health = 200,
			 armor = 0,
			 walkspeed = 1.15,
			 runspeed = 1.15,
			 jumppower = 1.15,
			 vest = nil,
			 models = {"models/player/gman_high.mdl"},
			 showmodel = "models/player/gman_high.mdl",
			 pmcolor = Color(0,0,0),
			 flashlight = true,
			 level = 10,
			 max = 1,
			},
		}
	},
	support = {
		name = "Armed Site Support",
		color = Color(29, 81, 56),
		roles = {
			{name = ROLES.ROLE_MTFNTF, 
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "weapon_stunstick", "cw_ar15"},
			 showweapons = {"MTF Keycard", "Radio", "NVG", "Stunstick", "AR-15"},
			 keycard = "mtf",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_ntf",
			 models = SECURITYMODELS,
			 showmodel = "models/balkandude.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 5
			},
			{name = ROLES.ROLE_CHAOS, 
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "item_radio", "weapon_stunstick", "cw_ak74"},
			 showweapons = {"Hacked CI Keycard", "Radio", "Stunstick", "AK-74"},
			 keycard = "ci",
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_chaosins",
			 models = CHAOSMODELS,
			 showmodel = "models/chaos_insurgency_trooper/chaos_insurgency_trooper.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 5
			},
			{name = ROLES.ROLE_CHAOS_JUGGERNAUT,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "item_radio", "cw_gau_minigun"},
			 showweapons = {"Hacked CI Keycard", "Radio", "Minigun"},
			 keycard = "ci",
			 ammo = {},
			 health = 200,
			 armor = 0,
			 walkspeed = 0.25,
			 runspeed = 0.25,
			 jumppower = 0.25,
			 vest = "armor_chaosjugg",
			 models = CHAOSMODELS,
			 showmodel = "models/arty/codmw2022/mp/dmz/alqatala/juggernaut/juggernaut_pm.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 10,
			 max = 1
			}
		}
	},
	goc = {
		name = "Global Occult Coalition",
		color = Color(255, 255, 0),
		roles = {
			{name = ROLES.ROLE_GOC_SOLDIER,
			 team = TEAM_GOC,
			 weapons = {"br_holster", "br_id", "item_radio", "item_medkit", "weapon_stunstick", "cw_g36c"},
			 showweapons = {"GOC Keycard", "Radio", "Medkit", "Stunstick", "G36C"},
			 keycard = "omni",
			 ammo = {},
			 health = 120,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_goc",
			 models = {"models/player/cheddar/goc/goc_soldier2.mdl"},
			 showmodel = "models/player/cheddar/goc/goc_soldier2.mdl",
			 pmcolor = Color(255, 255, 0),
			 flashlight = true,
			 level = 10,
			 max = 8
			},
			{name = ROLES.ROLE_GOC_OPERATIVE,
			 team = TEAM_GOC,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "item_medkit", "weapon_stunstick", "cw_ar15"},
			 showweapons = {"GOC Keycard", "Radio", "NVG", "Medkit", "Stunstick", "AR-15"},
			 keycard = "omni",
			 ammo = {},
			 health = 130,
			 armor = 0,
			 walkspeed = 0.92,
			 runspeed = 0.97,
			 jumppower = 0.92,
			 vest = "armor_goc",
			 models = {"models/player/cheddar/goc/goc_soldier2.mdl"},
			 showmodel = "models/player/cheddar/goc/goc_soldier2.mdl",
			 pmcolor = Color(255, 255, 0),
			 flashlight = true,
			 level = 12,
			 max = 3
			},
			{name = ROLES.ROLE_GOC_COMMANDER,
			 team = TEAM_GOC,
			 weapons = {"br_holster", "br_id", "item_radio", "item_nvg", "item_cameraview", "weapon_stunstick", "cw_scarh"},
			 showweapons = {"GOC Commander Keycard", "Radio", "NVG", "Camera View", "Ultra Medkit", "Stunstick", "SCAR-H"},
			 keycard = "omni",
			 ammo = {},
			 health = 150,
			 armor = 0,
			 walkspeed = 0.95,
			 runspeed = 1.0,
			 jumppower = 0.95,
			 vest = "armor_goc",
			 models = {"models/player/cheddar/goc/goc_soldier2.mdl"},
			 showmodel = "models/player/cheddar/goc/goc_soldier2.mdl",
			 pmcolor = Color(255, 255, 0),
			 flashlight = true,
			 level = 15,
			 max = 1
			}
		}
	}
}
